name: orm_schema
description: A starting point for Dart libraries or applications.
version: 6.0.0-dev.1
# repository: https://github.com/my_org/my_repo

resolution: workspace
environment:
  sdk: ^3.10.1

dependencies:
  meta: ^1.17.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
